server:
  port: 8888
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
      
zuul:
  routes:
    employee-serivce:
      path: /emp-api/**
      url: http://localhost:8090/
    springboot-jwt-service:
      path: /jwt-api/**
      url: http://localhost:8081/        
    