
server:
  port: 8081

spring:
  application:
    name: springboot-jwt-service
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_jwt
    username: root
    password: tiger
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect